### ISSUE TITLE
Fix name

### ISSUE THREAD

**Issue by wasamasa** [mola-T/signal#2]
This is a pretty bad name as signals already mean something different in Emacs.  Please change it to something different.

**Comment by mola-T** [comment]
Interesting. I used package name sign.el but when I ask for approval on melpa, the maintainer advices me to use signal lol.

https://github.com/melpa/melpa/pull/3786

**Comment by wasamasa** [comment]
Except he didn't and suggested you to use `signals`.  That's one letter more...

**Comment by mola-T** [comment]
I feel `singal` and `signals` have no difference in terms of confusion XD. People just think signals is many signal. So I choose to use `signal` at the end.
